/**
 * Service for managing Value Models, Business Cases, and their related artifacts.
 * This service encapsulates business logic and uses repositories for data access.
 */
import { LifecycleContext } from '../types/agent';
import { TargetAgentOutput } from '../types/vos';
import { RoiModelRepository } from '../repositories/RoiModelRepository';
import { KpiTargetRepository } from '../repositories/KpiTargetRepository';
import { ValueTreeRepository } from '../repositories/ValueTreeRepository';
import { ValueTreeNodeRepository } from '../repositories/ValueTreeNodeRepository';
import { ValueTreeLinkRepository } from '../repositories/ValueTreeLinkRepository';
import { RoiModelCalculationRepository } from '../repositories/RoiModelCalculationRepository';
import { ValueCommitRepository } from '../repositories/ValueCommitRepository';
// We will also need an audit/provenance service, but that's a later refactoring.

export class ModelService {
  private context: LifecycleContext;
  private roiModelRepo: RoiModelRepository;
  private kpiTargetRepo: KpiTargetRepository;
  private valueTreeRepo: ValueTreeRepository;
  private valueTreeNodeRepo: ValueTreeNodeRepository;
  private valueTreeLinkRepo: ValueTreeLinkRepository;
  private roiModelCalcRepo: RoiModelCalculationRepository;
  private valueCommitRepo: ValueCommitRepository;

  constructor(context: LifecycleContext) {
    if (!context.organizationId) {
      throw new Error('Organization ID is required to initialize ModelService');
    }
    this.context = context;
    this.roiModelRepo = new RoiModelRepository(context.organizationId);
    this.kpiTargetRepo = new KpiTargetRepository(context.organizationId);
    this.valueTreeRepo = new ValueTreeRepository(context.organizationId);
    this.valueTreeNodeRepo = new ValueTreeNodeRepository(context.organizationId);
    this.valueTreeLinkRepo = new ValueTreeLinkRepository(context.organizationId);
    this.roiModelCalcRepo = new RoiModelCalculationRepository(context.organizationId);
    this.valueCommitRepo = new ValueCommitRepository(context.organizationId);
  }

  /**
   * Persists all artifacts generated by the TargetAgent.
   * This encapsulates the logic previously in `TargetAgent.persistTargetArtifacts`.
   * @param output The output from the TargetAgent.
   * @param valueCaseId The ID of the value case.
   */
  async persistBusinessCase(output: TargetAgentOutput, valueCaseId: string): Promise<{
    valueTreeId: string;
    roiModelId: string;
    valueCommitId: string;
  }> {
    // 1. Create Value Tree
    const { data: valueTreeData, error: treeError } = await this.valueTreeRepo.create({
      ...output.valueTree,
      value_case_id: valueCaseId
    });
    if (treeError) throw new Error(`Failed to create value tree: ${treeError.message}`);
    const valueTreeId = valueTreeData.id;
    // TODO: Log provenance for value_tree creation

    // 2. Create Value Tree Nodes and Links
    for (const node of output.businessCase.nodes) {
      await this.valueTreeNodeRepo.create({
        value_tree_id: valueTreeId,
        node_id: node.node_id,
        label: node.label,
        type: node.type,
        reference_id: node.reference_id,
        properties: {}
      });
    }
    for (const link of output.businessCase.links) {
      const { data: parentNode } = await this.valueTreeNodeRepo.findByNodeId(valueTreeId, link.parent_node_id);
      const { data: childNode } = await this.valueTreeNodeRepo.findByNodeId(valueTreeId, link.child_node_id);

      if (parentNode && childNode) {
        await this.valueTreeLinkRepo.create({
          value_tree_id: valueTreeId,
          parent_id: parentNode.id,
          child_id: childNode.id,
          link_type: 'drives',
          weight: link.weight || 1.0,
          metadata: {}
        });
      }
    }

    // 3. Create ROI Model
    const { data: roiModelData, error: roiError } = await this.roiModelRepo.create({
        ...output.roiModel,
        value_tree_id: valueTreeId,
    });
    if (roiError) throw new Error(`Failed to create ROI model: ${roiError.message}`);
    const roiModelId = roiModelData.id;
    // TODO: Log provenance for roi_model creation

    // 4. Create ROI Model Calculations
    for (const calc of output.businessCase.calculations) {
      await this.roiModelCalcRepo.create({
          roi_model_id: roiModelId,
          ...calc,
          input_variables: calc.input_variables || [],
          source_references: calc.source_references || {},
          reasoning_trace: calc.reasoning_trace || output.businessCase.reasoning
      });
      // TODO: Log provenance for calculation creation
    }

    // 5. Create Value Commit
    const { data: commitData, error: commitError } = await this.valueCommitRepo.create({
      ...output.valueCommit,
      value_tree_id: valueTreeId,
      value_case_id: valueCaseId
    });
    if (commitError) throw new Error(`Failed to create value commit: ${commitError.message}`);
    const valueCommitId = commitData.id;
    // TODO: Log provenance for value_commit creation

    // 6. Create KPI Targets
    for (const target of output.businessCase.kpi_targets) {
      await this.kpiTargetRepo.create({
        value_commit_id: valueCommitId,
        kpi_hypothesis_id: '', // This seems to be missing from the agent output
        ...target
      });
    }

    return { valueTreeId, roiModelId, valueCommitId };
  }
}