/**
 * Service for managing Value Models, Business Cases, and their related artifacts.
 * This service encapsulates business logic and uses repositories for data access.
 */
import { LifecycleContext } from '../types/agent';
import { TargetAgentOutput } from '../types/vos';
import { RoiModelRepository } from '../repositories/RoiModelRepository';
import { KpiTargetRepository } from '../repositories/KpiTargetRepository';
import { ValueTreeRepository } from '../repositories/ValueTreeRepository';
import { ValueTreeNodeRepository } from '../repositories/ValueTreeNodeRepository';
import { ValueTreeLinkRepository } from '../repositories/ValueTreeLinkRepository';
import { RoiModelCalculationRepository } from '../repositories/RoiModelCalculationRepository';
import { ValueCommitRepository } from '../repositories/ValueCommitRepository';
import { ProvenanceAuditRepository } from '../repositories/ProvenanceAuditRepository';

export class ModelService {
  private context: LifecycleContext;
  private roiModelRepo: RoiModelRepository;
  private kpiTargetRepo: KpiTargetRepository;
  private valueTreeRepo: ValueTreeRepository;
  private valueTreeNodeRepo: ValueTreeNodeRepository;
  private valueTreeLinkRepo: ValueTreeLinkRepository;
  private roiModelCalcRepo: RoiModelCalculationRepository;
  private valueCommitRepo: ValueCommitRepository;
  private provenanceRepo: ProvenanceAuditRepository;

  constructor(context: LifecycleContext) {
    if (!context.organizationId) {
      throw new Error('Organization ID is required to initialize ModelService');
    }
    this.context = context;
    this.roiModelRepo = new RoiModelRepository(context.organizationId);
    this.kpiTargetRepo = new KpiTargetRepository(context.organizationId);
    this.valueTreeRepo = new ValueTreeRepository(context.organizationId);
    this.valueTreeNodeRepo = new ValueTreeNodeRepository(context.organizationId);
    this.valueTreeLinkRepo = new ValueTreeLinkRepository(context.organizationId);
    this.roiModelCalcRepo = new RoiModelCalculationRepository(context.organizationId);
    this.valueCommitRepo = new ValueCommitRepository(context.organizationId);
    this.provenanceRepo = new ProvenanceAuditRepository();
  }

  /**
   * Persists all artifacts generated by the TargetAgent.
   * This encapsulates the logic previously in `TargetAgent.persistTargetArtifacts`.
   * @param output The output from the TargetAgent.
   * @param valueCaseId The ID of the value case.
   */
  async persistBusinessCase(output: TargetAgentOutput, valueCaseId: string): Promise<{
    valueTreeId: string;
    roiModelId: string;
    valueCommitId: string;
  }> {
    // 1. Create Value Tree
    const { data: valueTreeData, error: treeError } = await this.valueTreeRepo.create({
      ...output.valueTree,
      value_case_id: valueCaseId
    });
    if (treeError) throw new Error(`Failed to create value tree: ${treeError.message}`);
    const valueTreeId = valueTreeData.id;
    
    // Log provenance for value_tree creation
    try {
      await this.provenanceRepo.create({
        session_id: this.context.sessionId || 'unknown-session',
        agent_id: 'target-agent',
        artifact_type: 'value_tree',
        artifact_id: valueTreeId,
        action: 'created',
        reasoning_trace: output.businessCase?.reasoning || 'Value tree created from target agent output',
        artifact_data: {
          name: valueTreeData.name,
          value_case_id: valueCaseId,
          version: valueTreeData.version
        },
        input_variables: {},
        output_snapshot: {
          node_count: output.businessCase.nodes?.length || 0,
          link_count: output.businessCase.links?.length || 0
        }
      });
    } catch (provenanceError) {
      // Log but don't fail the operation if provenance logging fails
      console.error('Failed to log provenance for value_tree:', provenanceError);
    }

    // 2. Create Value Tree Nodes and Links
    for (const node of output.businessCase.nodes) {
      await this.valueTreeNodeRepo.create({
        value_tree_id: valueTreeId,
        node_id: node.node_id,
        label: node.label,
        type: node.type,
        reference_id: node.reference_id,
        properties: {}
      });
    }
    for (const link of output.businessCase.links) {
      const { data: parentNode } = await this.valueTreeNodeRepo.findByNodeId(valueTreeId, link.parent_node_id);
      const { data: childNode } = await this.valueTreeNodeRepo.findByNodeId(valueTreeId, link.child_node_id);

      if (parentNode && childNode) {
        await this.valueTreeLinkRepo.create({
          value_tree_id: valueTreeId,
          parent_id: parentNode.id,
          child_id: childNode.id,
          link_type: 'drives',
          weight: link.weight || 1.0,
          metadata: {}
        });
      }
    }

    // 3. Create ROI Model
    const { data: roiModelData, error: roiError } = await this.roiModelRepo.create({
        ...output.roiModel,
        value_tree_id: valueTreeId,
    });
    if (roiError) throw new Error(`Failed to create ROI model: ${roiError.message}`);
    const roiModelId = roiModelData.id;
    
    // Log provenance for roi_model creation
    try {
      await this.provenanceRepo.create({
        session_id: this.context.sessionId || 'unknown-session',
        agent_id: 'target-agent',
        artifact_type: 'roi_model',
        artifact_id: roiModelId,
        action: 'created',
        reasoning_trace: output.businessCase?.reasoning || 'ROI model created from target agent output',
        artifact_data: {
          value_tree_id: valueTreeId,
          name: roiModelData.name
        },
        input_variables: {
          value_tree_id: valueTreeId
        },
        output_snapshot: {
          total_benefit: roiModelData.total_benefit,
          total_cost: roiModelData.total_cost,
          net_value: roiModelData.net_value,
          roi_percentage: roiModelData.roi_percentage
        }
      });
    } catch (provenanceError) {
      // Log but don't fail the operation if provenance logging fails
      console.error('Failed to log provenance for roi_model:', provenanceError);
    }

    // 4. Create ROI Model Calculations
    for (const calc of output.businessCase.calculations) {
      const { data: calcData, error: calcError } = await this.roiModelCalcRepo.create({
          roi_model_id: roiModelId,
          ...calc,
          input_variables: calc.input_variables || [],
          source_references: calc.source_references || {},
          reasoning_trace: calc.reasoning_trace || output.businessCase.reasoning
      });
      
      if (calcError) {
        throw new Error(`Failed to create calculation: ${calcError.message}`);
      }
      
      // Log provenance for calculation creation
      if (calcData) {
        try {
          // Convert input_variables array to Record for provenance logging
          const inputVarsRecord: Record<string, any> = {};
          if (Array.isArray(calc.input_variables)) {
            calc.input_variables.forEach((v, idx) => {
              inputVarsRecord[v.name || `var_${idx}`] = v.source || v.description || 'unknown';
            });
          }
          
          await this.provenanceRepo.create({
            session_id: this.context.sessionId || 'unknown-session',
            agent_id: 'target-agent',
            artifact_type: 'roi_calculation',
            artifact_id: calcData.id,
            action: 'created',
            reasoning_trace: calc.reasoning_trace || output.businessCase?.reasoning || 'ROI calculation created',
            artifact_data: {
              roi_model_id: roiModelId,
              calculation_type: calc.calculation_type
            },
            input_variables: inputVarsRecord,
            output_snapshot: {
              formula: calc.formula,
              result_value: calc.result_value
            }
          });
        } catch (provenanceError) {
          // Log but don't fail the operation if provenance logging fails
          console.error('Failed to log provenance for roi_calculation:', provenanceError);
        }
      }
    }

    // 5. Create Value Commit
    const { data: commitData, error: commitError } = await this.valueCommitRepo.create({
      ...output.valueCommit,
      value_tree_id: valueTreeId,
      value_case_id: valueCaseId
    });
    if (commitError) throw new Error(`Failed to create value commit: ${commitError.message}`);
    const valueCommitId = commitData.id;
    
    // Log provenance for value_commit creation
    try {
      await this.provenanceRepo.create({
        session_id: this.context.sessionId || 'unknown-session',
        agent_id: 'target-agent',
        artifact_type: 'value_commit',
        artifact_id: valueCommitId,
        action: 'created',
        reasoning_trace: output.businessCase?.reasoning || 'Value commit created from target agent output',
        artifact_data: {
          value_tree_id: valueTreeId,
          value_case_id: valueCaseId,
          target_date: commitData.target_date,
          status: commitData.status
        },
        input_variables: {
          value_tree_id: valueTreeId,
          roi_model_id: roiModelId
        },
        output_snapshot: {
          committed_value: commitData.committed_value,
          confidence_level: commitData.confidence_level
        }
      });
    } catch (provenanceError) {
      // Log but don't fail the operation if provenance logging fails
      console.error('Failed to log provenance for value_commit:', provenanceError);
    }

    // 6. Create KPI Targets
    for (const target of output.businessCase.kpi_targets) {
      await this.kpiTargetRepo.create({
        value_commit_id: valueCommitId,
        kpi_hypothesis_id: '', // This seems to be missing from the agent output
        ...target
      });
    }

    return { valueTreeId, roiModelId, valueCommitId };
  }
}