/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Kubernetes liveness probe endpoint
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                            /** Format: date-time */
                            timestamp?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Kubernetes readiness probe endpoint
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ready */
                            status?: string;
                            checks?: {
                                name?: string;
                                /** @enum {string} */
                                status?: "healthy" | "unhealthy";
                                latency?: number;
                            }[];
                        };
                    };
                };
                /** @description Service is not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canvas/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate business model canvas
         * @description Generate a complete business model canvas using AI
         */
        post: operations["generateCanvas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canvas/{canvasId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get canvas by ID */
        get: operations["getCanvas"];
        /** Update canvas */
        put: operations["updateCanvas"];
        post?: never;
        /** Delete canvas */
        delete: operations["deleteCanvas"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/canvas/{canvasId}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine canvas section
         * @description Get AI-powered suggestions to improve a canvas section
         */
        post: operations["refineCanvas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send LLM chat request
         * @description Send a chat completion request to LLM with automatic fallback
         */
        post: operations["llmChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get LLM statistics
         * @description Get statistics about LLM usage and circuit breaker status
         */
        get: operations["getLLMStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check LLM service health
         * @description Check health of LLM providers and circuit breakers
         */
        get: operations["getLLMHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/llm-usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user LLM usage
         * @description Get LLM usage statistics for the authenticated user
         */
        get: operations["getUserLLMUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List prompt versions
         * @description List all versions for a prompt key
         */
        get: operations["listPromptVersions"];
        put?: never;
        /**
         * Create prompt version
         * @description Create a new version of a prompt
         */
        post: operations["createPromptVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prompts/versions/{promptKey}/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate prompt version
         * @description Activate a specific version of a prompt
         */
        post: operations["activatePromptVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Canvas: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            userId?: string;
            businessDescription?: string;
            keyPartners?: string[];
            keyActivities?: string[];
            valuePropositions?: string[];
            customerRelationships?: string[];
            customerSegments?: string[];
            keyResources?: string[];
            channels?: string[];
            costStructure?: string[];
            revenueStreams?: string[];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PromptVersion: {
            /** Format: uuid */
            id?: string;
            promptKey?: string;
            version?: number;
            template?: string;
            variables?: string[];
            metadata?: Record<string, never>;
            performance?: {
                avgLatency?: number;
                avgCost?: number;
                successRate?: number;
                userSatisfaction?: number;
            };
            /** @enum {string} */
            status?: "draft" | "testing" | "active" | "deprecated";
            /** Format: date-time */
            createdAt?: string;
        };
        ProviderStats: {
            /** @enum {string} */
            state?: "open" | "half-open" | "closed";
            calls?: number;
            failures?: number;
            fallbacks?: number;
        };
        ProviderHealth: {
            healthy?: boolean;
            /** @enum {string} */
            state?: "open" | "half-open" | "closed";
        };
        Error: {
            error?: string;
            message?: string;
            details?: Record<string, never>;
        };
        RateLimitError: {
            /** @example Rate limit exceeded */
            error?: string;
            message?: string;
            /** @example /pricing */
            upgradeUrl?: string;
            /** @description Seconds until rate limit resets */
            retryAfter?: number;
        };
    };
    responses: {
        /** @description Authentication required */
        UnauthorizedError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Unauthorized",
                 *       "message": "Authentication token required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Insufficient permissions */
        ForbiddenError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Forbidden",
                 *       "message": "Insufficient permissions"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFoundError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Not Found",
                 *       "message": "Resource not found"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimitError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RateLimitError"];
            };
        };
    };
    parameters: {
        /** @description Page number */
        PageParam: number;
        /** @description Items per page */
        LimitParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateCanvas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Description of the business
                     * @example A SaaS platform for project management
                     */
                    businessDescription: string;
                    /**
                     * @description Industry sector
                     * @example Technology
                     */
                    industry?: string;
                    /**
                     * @description Target market segment
                     * @example SMBs
                     */
                    targetMarket?: string;
                    /**
                     * @description LLM model to use
                     * @default meta-llama/Llama-3-70b-chat-hf
                     * @enum {string}
                     */
                    model?: "meta-llama/Llama-3-70b-chat-hf" | "meta-llama/Llama-3-8b-chat-hf" | "mistralai/Mixtral-8x7B-Instruct-v0.1";
                };
            };
        };
        responses: {
            /** @description Canvas generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        data?: {
                            /** Format: uuid */
                            canvasId?: string;
                            canvas?: components["schemas"]["Canvas"];
                            /** @enum {string} */
                            provider?: "together_ai" | "openai" | "cache";
                            /**
                             * Format: float
                             * @example 0.002
                             */
                            cost?: number;
                            /** @example 1500 */
                            latency?: number;
                            cached?: boolean;
                        };
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitError"];
                };
            };
            /** @description LLM service unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCanvas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvasId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canvas retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: components["schemas"]["Canvas"];
                    };
                };
            };
            /** @description Canvas not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateCanvas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvasId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Canvas"];
            };
        };
        responses: {
            /** @description Canvas updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: components["schemas"]["Canvas"];
                    };
                };
            };
        };
    };
    deleteCanvas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvasId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Canvas deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
    refineCanvas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvasId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    section: "keyPartners" | "keyActivities" | "valuePropositions" | "customerRelationships" | "customerSegments" | "keyResources" | "channels" | "costStructure" | "revenueStreams";
                    /**
                     * @description Additional context for refinement
                     * @example We want to expand into enterprise market
                     */
                    context?: string;
                };
            };
        };
        responses: {
            /** @description Suggestions generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: {
                            suggestions?: string[];
                            reasoning?: string;
                            cost?: number;
                            cached?: boolean;
                        };
                    };
                };
            };
        };
    };
    llmChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description The prompt to send to the LLM */
                    prompt: string;
                    /**
                     * @description LLM model to use
                     * @example meta-llama/Llama-3-70b-chat-hf
                     */
                    model: string;
                    /** @default 1000 */
                    maxTokens?: number;
                    /**
                     * Format: float
                     * @default 0.7
                     */
                    temperature?: number;
                };
            };
        };
        responses: {
            /** @description LLM response generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: {
                            content?: string;
                            /** @enum {string} */
                            provider?: "together_ai" | "openai" | "cache";
                            model?: string;
                            usage?: {
                                promptTokens?: number;
                                completionTokens?: number;
                                totalTokens?: number;
                            };
                            /** Format: float */
                            cost?: number;
                            latency?: number;
                            cached?: boolean;
                        };
                    };
                };
            };
        };
    };
    getLLMStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: {
                            togetherAI?: components["schemas"]["ProviderStats"];
                            openAI?: components["schemas"]["ProviderStats"];
                            cache?: {
                                hits?: number;
                                misses?: number;
                            };
                        };
                    };
                };
            };
        };
    };
    getLLMHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All providers healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: {
                            togetherAI?: components["schemas"]["ProviderHealth"];
                            openAI?: components["schemas"]["ProviderHealth"];
                        };
                    };
                };
            };
            /** @description One or more providers unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getUserLLMUsage: {
        parameters: {
            query?: {
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage statistics retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: {
                            /** Format: float */
                            totalCost?: number;
                            requestCount?: number;
                            tokenUsage?: {
                                prompt?: number;
                                completion?: number;
                                total?: number;
                            };
                            byModel?: {
                                model?: string;
                                requests?: number;
                                cost?: number;
                            }[];
                        };
                    };
                };
            };
        };
    };
    listPromptVersions: {
        parameters: {
            query: {
                promptKey: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Versions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: components["schemas"]["PromptVersion"][];
                    };
                };
            };
        };
    };
    createPromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example canvas.generate */
                    promptKey: string;
                    /** @example Generate a canvas for {{businessDescription}} */
                    template: string;
                    /**
                     * @example [
                     *       "businessDescription",
                     *       "industry"
                     *     ]
                     */
                    variables: string[];
                    metadata: {
                        author?: string;
                        description?: string;
                        tags?: string[];
                        model?: string;
                    };
                };
            };
        };
        responses: {
            /** @description Version created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        data?: components["schemas"]["PromptVersion"];
                    };
                };
            };
        };
    };
    activatePromptVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptKey: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version activated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
        };
    };
}
